
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jsucyxcsgmwudiumzeye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzdWN5eGNzZ213dWRpdW16ZXllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MDY0NzYsImV4cCI6MjA1ODA4MjQ3Nn0.f-hPxF6swRx6qTVwtZWoOhCJGNnUk103dbUW2qvSu94";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
